workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      node: latest
      vars:
        XCODE_WORKSPACE: "NetworkInfoAppRN.xcworkspace"
        XCODE_SCHEME: "NetworkInfoAppRN"
        PACKAGE_PATH: "NetworkInfoAppRN"
    scripts:
      - name: Set up code signing settings
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.example.NetworkInfoApp" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Install dependencies
        script: |
          cd $PACKAGE_PATH
          npm ci
      - name: Install iOS dependencies
        script: |
          cd $PACKAGE_PATH/ios
          pod install
      - name: Build iOS app
        script: |
          cd $PACKAGE_PATH/ios
          xcodebuild build -workspace $XCODE_WORKSPACE \
                          -scheme $XCODE_SCHEME \
                          -configuration Release \
                          -destination generic/platform=iOS \
                          -derivedDataPath build \
                          -archivePath build/NetworkInfoAppRN.xcarchive \
                          clean archive
      - name: Build iOS app IPA
        script: |
          cd $PACKAGE_PATH/ios
          xcodebuild -exportArchive \
                      -archivePath build/NetworkInfoAppRN.xcarchive \
                      -exportPath build/NetworkInfoAppRN \
                      -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/NetworkInfoAppRN.xcarchive
      - build/NetworkInfoAppRN/*.ipa
      - build/NetworkInfoAppRN/ExportOptions.plist
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
      email:
        recipients:
          - $EMAIL_RECIPIENT
