workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      node: latest
      vars:
        XCODE_WORKSPACE: "NetworkInfoAppRN.xcworkspace"
        XCODE_SCHEME: "NetworkInfoAppRN"
    scripts:
      - name: Install dependencies
        script: |
          cd NetworkInfoAppRN
          npm ci
      - name: Install iOS dependencies
        script: |
          cd NetworkInfoAppRN/ios
          pod install
      - name: Build iOS app
        script: |
          cd NetworkInfoAppRN/ios
          xcodebuild build -workspace $XCODE_WORKSPACE \
                          -scheme $XCODE_SCHEME \
                          -configuration Debug \
                          -destination generic/platform=iOS \
                          -derivedDataPath build \
                          clean build
    artifacts:
      - NetworkInfoAppRN/ios/build/
      - NetworkInfoAppRN/ios/build.log
